spring.application.name=dashbaord

# DATABASE CONFIG (NEON)

spring.datasource.url=jdbc:postgresql://ep-blue-pond-amgt5gdn-pooler.c-5.us-east-1.aws.neon.tech/neondb?sslmode=require&channelBinding=require
#spring.datasource.username=${DB_USERNAME}
spring.datasource.username=neondb_owner
#spring.datasource.password=${DB_PASSWORD}
spring.datasource.password=npg_bdC4Y7Dopnal
spring.datasource.driver-class-name=org.postgresql.Driver
server.port=8081
#JWT KEY
jwt.secret=my-super-secret-key-very-long-123456


# JPA / HIBERNATE

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect


# CONNECTION POOL (HikariCP)

spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.pool-name=FinancePool


# REDIS CONFIG

spring.cache.type=redis
spring.data.redis.host=localhost
spring.data.redis.port=6379


# SWAGGER CONFIG

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true